"""add task priority

Revision ID: 0cc26124ec61
Revises: 1de850e49eae
Create Date: 2026-08-26 16:57:30.567295

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc26124ec61"
down_revision: str | Sequence[str] | None = "1de850e49eae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "priority", sa.String(length=20), server_default="medium", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "priority")
    # ### end Alembic commands ###
